### ISSUE TITLE
Extension didn't receive Data in ModuleFacebookLogin.php

### ISSUE THREAD

**Issue by ideefixx** [codefog/contao-facebook_login#1]
The Extension works only when i replace the tags with a string in ModuleFacebookLogin.php

$arrData = array
        (
            'tstamp' => $time,
            'dateAdded' => $time,
            'firstname' => $arrProfile['first_name'], //didn't work
            'lastname' => $arrProfile['last_name'], //didn't work
            'gender' => $arrProfile['gender'], //didn't work
            'email' => $arrProfile['email'], //didn't work
            'login' => 1,
            'username' => 'fb_' . $arrProfile['id'],
            'fblogin' => $arrProfile['id'],
            'groups' => $this->reg_groups
        );

**Comment by qzminski** [comment]
Is your Facebook app allowed to fetch those data? Maybe there is some permission issue in its settings.

**Comment by ideefixx** [comment]
yes, the app is allowed to fetch. 
We've testet with Contao 3.5.
If you have a Screenshot with an working example, we can also match it.

**Comment by qzminski** [comment]
At the moment I am not able to setup the test environment, so I can't fix it right now. It's very likely that Facebook has changed something in the API. I'll leave this open for the future fix.

If you are going to debug it yourself please share your dicoveries.

**Comment by ideefixx** [comment]
i've tested the facebook api by this way:
https://graph.facebook.com/1000100123456789?key=value&access_token=1234567890123456789|234b755095z9b7ay53158702de0b808c

with all permissions it will return a Array like this:

{
   "name": "Mr Example",
   "id": "1000100123456789"
}

So we think facebook change the terms and fitted the API also.
Now we realized the FB:Login with a Fallback in the Template:

if (TL_MODE == 'FE')
{
   $this->import('FrontendUser', 'Member');
   if ($this->Member->email != '')
   {
       header('Location: path/to/userData/Module');
   }
}

not nice, but it works for us.

**Comment by ideefixx** [comment]
good news 4 you, its just a simple string

-> ModuleFacebookLogin.php
replace in protected function loginWithFacebook()

## replace this:

try
{
    $arrProfile = $objFacebook->api('/me');
}

## with this:

try
{
    $arrProfile = $objFacebook->api('/me?fields=id,name,first_name,last_name,email,gender');
}

**Comment by qzminski** [comment]
I have fixed it in ed40fe8. Can you confirm the fix is correct and it's working?

**Comment by ideefixx** [comment]
yeah,
it's tested on contao 3.5 with the library of facebook_login 1.0.3,
but i think you'll should implement a fallback also. some user's register a facebook account without an email adress, so they only have a phone number. you can fix it with a simple fallback/dummy address in this case. i fixed it this way.
also it's necessary for some coutries to implement a checkbox for terms of use (with a simple jquery script to activate the button after checking).

**Comment by qzminski** [comment]
I don't think it's a good idea to use a dummy e-mail address. If they do not have any, then they should consider registering the traditional way in Contao or updating the personal details right after the registration via Facebook.
