### ISSUE TITLE
Column 'email' cannot be null 

### ISSUE THREAD

**Issue by sidyamamoto** [codefog/contao-facebook_login#2]
Got error "Column 'email' cannot be null " when running facebook login. I don't know if this error is caused by using mailusername extension and facebook_login together. Temporarily changed the column manually in DB, but I guess it's not a very good idea to leave it like this.

**Comment by sidyamamoto** [comment]
Just looked into Facebook docs and looks like sometimes email might be empty. Reference: https://developers.facebook.com/docs/facebook-login/permissions/v2.2#reference-email)
_"Note, even if you request the email permission it is not guaranteed you will get an email address. For example, if someone signed up for Facebook with a phone number instead of an email address, the email field may be empty."_

**Comment by qzminski** [comment]
I am not sure what we can do about it because the e-mail address in Contao is required for every member and used in many processes. Since your case is an edge one I'll close this task for now as there is no clear solution for this.
