### ISSUE TITLE
User home dir not created

### ISSUE THREAD

**Issue by JLNNN** [codefog/contao-facebook_login#3]
Hi,
is the user's home directory not created on login? I didn't find any code that's doing that - and folders aren't created on my webserver, too.

Thanks in advance :)

**Comment by qzminski** [comment]
Ah no, apparently not - shall I add that feature?

**Comment by JLNNN** [comment]
That would be very nice :)

**Comment by qzminski** [comment]
Fixed in ae96cd5. The extension in the Extension Repository has been also updated.
