### ISSUE TITLE
Facebook login without popup

### ISSUE THREAD

**Issue by JLNNN** [codefog/contao-facebook_login#4]
Hey,
is it possible that you can add a Facebook login without a popup? I already implemented it on my own page with your module, but because the redirect_uri parameter is stripping everything that's after the question mark in the query parameter, it's currently impossible to do a PHP-only version. So I used the state parameter.

facebook_login/templates/modules/mod_facebook_login.html5, line 28 following:

``` javascript
// FB.login(function(response) {
//  if (response.status === 'connected') {
//      window.location = url;
//  }
// }, {scope: 'email'});
window.location = encodeURI("https://www.facebook.com/dialog/oauth?client_id=<?php echo $this->appId; ?>&redirect_uri="+url+"&response_type=token&scope=email&state=fblogin");
```

And an additional javascript function:

``` javascript
    checkFBLogin: function() {
      function getHashValue(key) {
        var matches = location.hash.match(new RegExp(key+'=([^&]*)'));
        return matches ? matches[1] : null;
      }

      if (getHashValue('state') == "fblogin") {
        var $button = $(".mod_facebook_login > a");
        $button.before("<div class='success'><p>Please try again.</p></div>");
      }
    }
```

This is already working fine, but you always have to press the "Login with Facebook" button twice if you're using the login the first time with your Facebook account.

Another important fact: You can't use the popup version on iOS if you're not using the Safari browser.

Thanks in advance and keep up the great work!

Greetings from Germany, Julian

**Comment by qzminski** [comment]
I don't know to be honest. This module was developed ages ago and the Facebook login must have changed since then.

> This is already working fine, but you always have to press the "Login with Facebook" button twice if you're using the login the first time with your Facebook account.

Press it twice? That does not sound good. How the user will know he needs to do that? Is there any message displayed?

> Another important fact: You can't use the popup version on iOS if you're not using the Safari browser.

Can you refer to the source of that fact? Is it stated in the Facebook docs?

**Comment by JLNNN** [comment]
On my site, you have to press the "Login with Facebook" button once, then you are being redirected to the login page on Facebook, there you accept the app and are being redirected again to my site. Here you have to press the button again now, because the PHP script isn't being executed, because the redirect_uri is stripping everything that's in the query parameter.

Here's a screenshot of the message I get when I try to use the (original) popup version on Chrome in iOS:

![foto-28 06](https://cloud.githubusercontent.com/assets/1099235/16432574/dd33858c-3d85-11e6-846f-76d1f64893e7.jpg)

**Comment by mexmano** [comment]
Did you find a solution to open the FB Link with one click on the first time?

**Comment by qzminski** [comment]
Can you guys try 3417733? I don't have any development environment at the moment.

> Here you have to press the button again now, because the PHP script isn't being executed, because the redirect_uri is stripping everything that's in the query parameter.

I think that's because you have not encoded the passed URI correctly as characters such as `?` or `&` were not encoded and thus incorrectly parsed by the server.

**Comment by qzminski** [comment]
This extension is no longer maintained.
