### ISSUE TITLE
Contao 4 compatibility

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-facebook_login#7]
As mentioned in https://github.com/contao/core-bundle/pull/1159 the Extension does not work in Contao 4 because the `FrontendUser` class cannot be overridden anymore.

I was thinking of making a PR, where I would get rid of this requirement and "simply" do everything that is needed to log in a user manually. i.e. directly altering `tl_session` and setting the `FE_USER_AUTH` cookie etc.

**Comment by qzminski** [comment]
PR would be very welcome. You can take an example from my recent project: https://gist.github.com/qzminski/18b0628b7a3411717433a29e8aeea07b

**Comment by fritzmg** [comment]
I ended up creating my own bundle, if you don't mind :) https://github.com/inspiredminds/contao-facebook-login

**Comment by qzminski** [comment]
Hey that's great @fritzmg! I have added a link to your bundle to the readme for the last version of this extension.

https://github.com/codefog/contao-facebook_login/tree/develop#contao-4-compatibility
